---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: LoadBalancer
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: ankit090701/lne-node:latest
          ports:
            - containerPort: 80
          env:
            - name: DBHOST
              value: amfs.mysql.database.azure.com
            - name: DBUSERNAME
              value: ankit090701
            - name: DBPASSWORD
              value: Drowssap@3302
            - name: DBDIALECT
              value: mysql
            - name: DBNAME
              value: nodeemp
            - name: DBPORT
              value: "3306"
            - name: APPLICATION_HOST
              value: "0.0.0.0"
            - name: APPLICATION_PORT
              value: "80"
            - name: NODE_ENV
              value: production
            - name: WHITELIST_URLS
              value: "*"
